config/routes.rb
Rails.application.routes.draw do
  resources :weathers
  get 'event/index'
  get 'meetup/index'
  get 'books/index'
  get 'books/show'
  get 'books/new'
  get 'books/edit'
  #resources :profiles
  resources :profiles do
    resources:trips
  end  
  resources:trips
  get 'index3' => 'trips#index2'
 
  get 'newsearch' => 'event#newsearch'


  
   resources :profiles do
    resources:books
  end  
  
  resources:books
  
  get 'findlift' => 'trips#findlift'
  get 'weather' => 'weathers#weather'
  get 'weathertest' => 'weathers#weather2'
  match 'searchweather', to: 'weathers#getinfoweather', via: [:get, :post]
  

    
  devise_for :users
  root :to => 'home#index'
  get 'home/index'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :books    
  has_many :profiles
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @profile = Profile.find_by_user_id(current_user.id)
    @trips = @profile.trips
  end
  
  def index2
   
  end
  
  # GET /trips/1
  # GET /trips/1.json
  def show
    @profile = Profile.find_by_user_id(current_user.id)
    @trip = @profile.trips.find(params[:id])
  end

  # GET /trips/new
  def new
    @profile = Profile.find_by_user_id(current_user.id)
    @trip = @profile.trips.build
  end

  # GET /trips/1/edit
  def edit
    @profile = Profile.find_by_user_id(current_user.id)
    @trip = @profile.trips.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @profile = Profile.find_by_user_id(current_user.id)
    @trip = @profile.trips.build(params.require(:trip).permit(:date, :time, :pickup_location, :destination, :price, :seats_available, :driver_id, :profile_id))
    if @trip.save
      redirect_to profile_trip_url(@profile, @trip)
    else
     render :action => "new"
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    @profile = Profile.find_by_user_id(current_user.id)
    @trip = Trip.find(params[:id])
    if @trip.update_attributes(params.require(:trip).permit(:date, :time, :pickup_location, :destination, :price, :seats_available, :driver_id, :profile_id))
      redirect_to profile_trip_url(@profile, @trip)
    else
      render :action => "edit"
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @profile = Profile.find_by_user_id(current_user.id)
    @trip = Trip.find(params[:id])
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to profile_trips_path(@profile) }
      format.xml { head :ok }
    end
  end
  
  def findlift
     @trips = Trip.all
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:date, :time, :pickup_location, :destination, :price, :seats_available, :driver_id, :profile_id)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= javascript_include_tag 'trips'%>


<%= form_for([@profile, @trip]) do |form| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>
      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.label :date%>
    <%= form.date_field :date, class: "form-control", id: "date"%>
 </div>
 
  <div class="field">
    <%= form.label :time %>
    <%= form.time_field :time, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :pickup_location %>
    <%= form.text_field :pickup_location , class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :seats_available %>
    <%= form.text_field :seats_available, class: 'form-control' %>
  </div>

  <div class="actions">
     <%= form.submit 'Create a Trip', class: 'btn btn-success' %>
  </div>
 
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<div style="text-align:center">
    <%= link_to 'Back', trips_path, class: "btn btn-primary" %>
</div>

app/views/trips/findlift.html.erb
<h1>Trips Available</h1>
<table class="center table-striped table-dark">
  <thead>
    <tr class="bg-primary">
      <th>Date</th>
      <th>Time</th>
      <th>Price</th>
      <th>Seats available</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr >
        <td><%= trip.date %></td>
        <td><%= trip.time %></td>
        <td><%= trip.price %></td>
        <td><%= trip.seats_available %></td>
        <td><%= link_to 'Book', new_book_path(:id => trip.id), :class => 'btn btn-primary' %></td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/trips/index.html.1.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
<% if @trips.empty? %>
 <h1>No trips found</h1>
<% else %>
 <h1>Trips</h1>
<table class="center table-striped table-dark">
  <thead>
    <tr class="bg-primary">
      <th>Date</th>
      <th>Time</th>
      <th>Price</th>
      <th>Seats available</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr >
        <td><%= trip.date %></td>
        <td><%= trip.time %></td>
        <td><%= trip.price %></td>
        <td><%= trip.seats_available %></td>
        <td><%= link_to 'show', profile_trip_path(@profile, trip), :class => 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_profile_trip_path(@profile, trip), :class => 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', profile_trip_path(@profile, trip), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

<div style="text-align:center">
    <%= link_to 'New Trip',new_profile_trip_path(@profile,@trip), class: "btn btn-primary" %>
</div>

<% end %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
<% if @trips.empty? %>
 <h1>No trips found</h1>
<% else %>
 <h1>Trips</h1>
<table class="center table-striped table-dark">
  <thead>
    <tr class="bg-primary">
      <th>Date</th>
      <th>Time</th>
      <th>Price</th>
      <th>Seats available</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr >
        <td><%= trip.date %></td>
        <td><%= trip.time %></td>
        <td><%= trip.price %></td>
        <td><%= trip.seats_available %></td>
        <td><%= link_to 'show', profile_trip_path(@profile, trip), :class => 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_profile_trip_path(@profile, trip), :class => 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', profile_trip_path(@profile, trip), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end %>

<div style="text-align:center">
    <%= link_to 'New Trip',new_profile_trip_path(@profile,@trip), class: "btn btn-primary" %>
</div>

<% end %>

app/views/trips/index2.html.erb
  <select id="country">
            <option value="0">R8</option>
            <option value="1">Quattro</option>
            <option value="2">A6 hatchback</option>
    </select>
    

app/views/trips/new.html.erb
<h1>Offer a Lift</h1>

<%= render 'form'%>

<div style="text-align:center">
    <%= link_to 'Back', profile_trips_path(@profile), class: "btn btn-primary" %>
</div>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<table class="center table-striped table-dark">
  <tr class="bg-primary" >
    <th colspan="2">Trip Details</th>
  </tr>
  <tr>
  
  <tr>
    <td>Date</td>
    <td> <%= @trip.date %></td> 
  </tr>
  <tr>
    <td>Time</td>
    <td> <%= @trip.time %></td> 
  </tr>
  <tr>
   <td>Pickup location</td> 
    <td><%= @trip.pickup_location %></td>
  </tr>
  <tr>
  <td>Destination</td> 
    <td><%= @trip.destination %></td>
  </tr>
  <td>Price</td> 
    <td> <%= @trip.price %></td> 
  </tr>
  <td>Seats available</td> 
    <td> <%= @trip.seats_available %></td> 
  </tr>
</table>

<div style="text-align:center">
  <%= link_to 'Edit', edit_trip_path(@trip), class: "btn btn-primary" %> |
  <%= link_to 'Back', trips_path, class: "btn btn-primary" %>
</div>