config/routes.rb
Rails.application.routes.draw do
  resources :weathers
  get 'event/index'
  get 'meetup/index'
  get 'books/index'
  get 'books/show'
  get 'books/new'
  get 'books/edit'
  #resources :profiles
  resources :profiles do
    resources:trips
  end  
  resources:trips
  get 'index3' => 'trips#index2'
 
  get 'newsearch' => 'event#newsearch'


  
   resources :profiles do
    resources:books
  end  
  
  resources:books
  
  get 'findlift' => 'trips#findlift'
  get 'weather' => 'weathers#weather'
  get 'weathertest' => 'weathers#weather2'
  match 'searchweather', to: 'weathers#getinfoweather', via: [:get, :post]
  

    
  devise_for :users
  root :to => 'home#index'
  get 'home/index'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :books
  has_many :trips
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profile = Profile.find_by_user_id(current_user.id)
    if @profile.nil?
        redirect_to new_profile_path
    else    
        redirect_to profile_path(current_user.id)
    end    
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    profile = Profile.find_by_user_id(current_user.id)
    if profile.nil?
      @profile = Profile.new
      @profile.user_id = current_user.id
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @profile }
      end
    else
      redirect_to profiles_path
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def signedinuserprofile
    profile = Profile.find_by_user_id(current_user.id)
    if profile.nil?
      redirect_to new_profile_path
    else
      @profile = Profile.find_by_user_id(current_user.id)
      redirect_to profiles_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
       @profile = Profile.find_by_user_id(current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :phonenumber, :location)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
    <div class="field">
      <%= form.label :'First Name', class: "control-label" %> 
      <%= form.text_field :firstname, class: 'form-control' %>
    </div>
  
    <div class="field">
      <%= form.label :'Last Name' %>
      <%= form.text_field :lastname, class: 'form-control' %>
    </div>
  
    <div class="field">
      <%= form.label :'Phone Number' %>
      <%= form.text_field :phonenumber, class: 'form-control' %>
    </div>
  
    <div class="field">
      <%= form.label :location %>
      <%= form.text_field :location, class: 'form-control' %>
    </div>
  
    <div class="actions">
      <%= form.submit 'Submit', class: 'btn btn-success' %>
    </div>
  </div>  
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit my Profile</h1>

<%= render 'form', profile: @profile %>

<div style="text-align:center">
  <%= link_to 'Back', profiles_path, class: "btn btn-primary" %> 
</div>

app/views/profiles/new.html.erb
<h1>Create a Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<table class="center table-striped table-dark">
  <tr class="bg-primary" >
    <th colspan="2">My Profile</th>
  </tr>
  <tr>
  
  <tr>
    <td>First Name</td>
    <td> <%= @profile.firstname %></td> 
  </tr>
  <tr>
    <td>Last Name</td>
    <td> <%= @profile.lastname %></td> 
  </tr>
  <tr>
   <td>Phone Number</td> 
    <td><%= @profile.phonenumber %></td>
  </tr>
  <tr>
  <td>Location</td> 
    <td><%= @profile.location %></td>
  </tr>

</table>

<div style="text-align:center">
  <%= link_to 'Edit', edit_profile_path(@profile), class: "btn btn-primary" %> 
</div>

<div style="text-align:center">
    <%= link_to 'New Book',new_profile_book_path(@profile,@book), class: "btn btn-primary" %>
</div>