config/routes.rb
Rails.application.routes.draw do
  resources :weathers
  get 'event/index'
  get 'meetup/index'
  get 'books/index'
  get 'books/show'
  get 'books/new'
  get 'books/edit'
  #resources :profiles
  resources :profiles do
    resources:trips
  end  
  resources:trips
  get 'index3' => 'trips#index2'
 
  get 'newsearch' => 'event#newsearch'


  
   resources :profiles do
    resources:books
  end  
  
  resources:books
  
  get 'findlift' => 'trips#findlift'
  get 'weather' => 'weathers#weather'
  get 'weathertest' => 'weathers#weather2'
  match 'searchweather', to: 'weathers#getinfoweather', via: [:get, :post]
  

    
  devise_for :users
  root :to => 'home#index'
  get 'home/index'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :profile
  belongs_to :trip
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    
    @profile = Profile.find_by_user_id(current_user.id)
    @books = @profile.books
  end

  def show
   # @profile = Profile.find_by_user_id(current_user.id)
  #  @book = @profile.books.find(params[:id])
  @trip = Trip.find(params[:id])

   
  end

  def new
    @profile = Profile.find_by_user_id(current_user.id)
    @book = @profile.books.build
    if (params[:id]).nil?
      redirect_to home_index_path, notice: 'No trip found.'
    else 
          @trip = Trip.find(params[:id])
    end      
  end
  
 def create
  params[:book][:status] = 'Pending Payment'
  nbSeats = params[:book][:seats].to_i
  @trip = Trip.find(params[:book][:trip_id] )
  params[:book][:total]  = nbSeats*@trip.price
  @profile = Profile.find_by_user_id(current_user.id)
  if @profile.id == @trip.profile_id
     redirect_to '/findlift'	, notice: 'You can not make this reservation.'
  else    
      @book = @profile.books.build(params.require(:book).permit(:status, :total, :seats, :trip_id))
      @book.save
      redirect_to home_index_path, notice: 'Booking was successfully created.'
  end    
 end
  
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Booking was successfully canceled.' }
      format.json { head :no_content }
    end
  end

 private

  def book_params
    params.require(:book).permit(:status, :total, :seats, :trip_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for([@profile, @book]) do |form| %>
        <ul class="list-group">
  <li class="list-group-item active"><%= @trip.date %></li>
  <li class="list-group-item">From: <%= @trip.pickup_location %> </li>
  <li class="list-group-item">To: <%= @trip.destination %> </li>
  <li class="list-group-item">Price(per seat): €<%= @trip.price %> </li>
</ul>

  
 <div class="field">
    <%= form.label :'Number of seats' %>
    <%= form.text_field :seats , class: 'form-control' %>
 </div>
 <%= form.hidden_field :trip_id, :value => @trip.id %>





    <div class="actions">
     <%= form.submit 'Book a Trip', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
 <h1>Booked</h1>
<table class="center table-striped table-dark">
  <thead>
    <tr class="bg-primary">
      <th>Status</th>
      <th>Total</th>
      <th>Seats</th>
      <th>Trip ID</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr >
        <td><%= book.status %></td>
        <td><%= book.total %></td>
        <td><%= book.seats %></td>
        <td><%= book.trip_id %></td>
        <td><%= link_to 'show', book_path(:id => book.trip_id), :class => 'btn btn-primary' %></td>

       </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/books/new.html.erb
<h1>Book a Lift</h1>

<%= render 'form', trip: @trip %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<table class="center table-striped table-dark">
  <tr class="bg-primary" >
    <th colspan="2">Trip Details</th>
  </tr>
  <tr>
  
  <tr>
    <td>Date</td>
    <td> <%= @trip.date %></td> 
  </tr>
  <tr>
    <td>Time</td>
    <td> <%= @trip.time %></td> 
  </tr>
  <tr>
   <td>Pickup location</td> 
    <td><%= @trip.pickup_location %></td>
  </tr>
  <tr>
  <td>Destination</td> 
    <td><%= @trip.destination %></td>
  </tr>
  <td>Price</td> 
    <td> <%= @trip.price %></td> 
  </tr>
  <td>Seats available</td> 
    <td> <%= @trip.seats_available %></td> 
  </tr>
</table>

<div style="text-align:center">
  <%= link_to 'Edit', edit_trip_path(@trip), class: "btn btn-primary" %> |
  <%= link_to 'Back', trips_path, class: "btn btn-primary" %>
</div>